export const doctorList = [
  {
    id: 1,
    name: "Dr. Sachin Desai",
    code: "drl00000001",
    city: "mumbai",
    state: "maharashtra",
    speciality: "General Physician",
  },
  {
    id: 2,
    name: "Dr. Vivek Vishwakarma",
    code: "drl00000002",
    city: "mumbai",
    state: "maharashtra",
    speciality: "General Physician",
  },
  {
    id: 3,
    name: "Dr. Sushant Pitale",
    code: "drl00000003",
    city: "mumbai",
    state: "maharashtra",
    speciality: "General Physician",
  },
  {
    id: 4,
    name: "Dr. Avinash Jadhav",
    code: "drl00000004",
    city: "mumbai",
    state: "maharashtra",
    speciality: "General Physician",
  },
  {
    id: 5,
    name: "Dr. Surendra Sharma",
    code: "drl00000005",
    city: "mumbai",
    state: "maharashtra",
    speciality: "General Physician",
  },
  {
    id: 6,
    name: "Dr. Alex Nadar",
    code: "drl00000007",
    city: "mumbai",
    state: "maharashtra",
    speciality: "General Physician",
  },
  {
    id: 7,
    name: "Dr. John Smith",
    code: "drl00000008",
    city: "mumbai",
    state: "maharashtra",
    speciality: "General Physician",
  },
  {
    id: 8,
    name: "Dr. Mahesh Kale",
    code: "drl00000009",
    city: "mumbai",
    state: "maharashtra",
    speciality: "General Physician",
  },
  {
    id: 9,
    name: "Dr. Harshal Cheda",
    code: "drl0010",
    city: "mumbai",
    state: "maharashtra",
    speciality: "General Physician",
  },
  {
    id: 10,
    name: "Dr. Sarosh Maldar",
    code: "drl0011",
    city: "mumbai",
    state: "maharashtra",
    speciality: "General Physician",
  },
];
